title: "Faruk Ahmed | Portfolio"
description: "Personal portfolio showcasing my projects, skills, and achievements"
author: "Faruk Ahmed"
email: "fa0713026@gmail.com"
url: "https://faruk0713.github.io/FarukAhmed.github.io/"
baseurl: ""   # keep empty since this is a user site

# Optional: if you want RSS and SEO
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

lang: en
timezone: Asia/Kolkata
